name: BookQuest
main: cc.isotopestudio.bookquest.BookQuest

author: Mars
description: BookQuest
website: http://isotopestudio.cc
version: 1.3.0
commands:
  quest:
    description: BookQuest
    usage: /<command>
  questaccept:
    description: BookQuest
    usage: /<command>
  questdecline:
    description: BookQuest
    usage: /<command>
